### ISSUE TITLE
Bikeshed appHistory.entries

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/history_api#16]
Does this clash with `entries` from iterables? Should it be `values`?

**Comment by domenic** [comment]
Since it's not an iterable, it doesn't seem so bad... although maybe it should be an iterable or maplike, with the `key` member being the key?? Hmm.

The name "history entry" has a long history in specs, but the app history API is the first time we'd be exposing it to web developers. So we could rename it to something like "item"...

**Comment by domenic** [comment]
Moving to https://github.com/slightlyoff/history_api/issues/16!
