### ISSUE TITLE
Update vs. replace and entry mutability.

### ISSUE THREAD

**Issue by StringEpsilon** [slightlyoff/history_api#21]
The description of `updateCurrentEntry()` suggests that the `AppHistoryEntry` instance will be mutated, rather than replaced. Is that correct?

This might cause unexpected behavior when navigating via `appHistory.navigateTo(key)`, as the key does not point to the previously associated location anymore. 

It might also cause issues on libraries or applications that assume (out of habit in regards to the current history API and NPM packages like `history`) that the location object is immutable. Thus being a (maybe slight) hurdle to migration, as a mutating location object might cause side effects or bugs in code not designed to handle that.

**Comment by domenic** [comment]
> The description of updateCurrentEntry() suggests that the AppHistoryEntry instance will be mutated, rather than replaced. Is that correct?

Hmm, interesting, I didn't think through this consequence. I'm not sure now. It kind of depends on what would be more useful. Thoughts welcome!

> This might cause unexpected behavior when navigating via appHistory.navigateTo(key), as the key does not point to the previously associated location anymore.

I'm not sure exactly what you mean by "previously associated location". It still points to the same history entry, but that history entry might have a different URL or `state` value than it used to.

In particular, this kind of suggests "update" is better than "replace". If we did "replace", then what would happen in the following scenario?

```js
const oldKey = appHistory.currentEntry.key;

// If this does a replace, then it will generate a new entry with a new key.
appHistory.replaceCurrentEntry({ state: "new state" });

console.assert(appHistory.currentEntry.key !== oldKey);

// What does this do?
await appHistory.navigateTo(oldKey);
```

The only reasonable behavior I can think of is to throw an exception. But that seems subpar; updating an entry's state shouldn't cause that entry to become non-navigable by its old key.

> the location object is immutable

How so? The `location` object's values change all the time, e.g. using `history.replaceState()`, or fragment navigation.

**Comment by StringEpsilon** [comment]
> I'm not sure exactly what you mean by "previously associated location". It still points to the same history entry, but that history entry might have a different URL or state value than it used to.

By location I mean the URL (path + hash + query). In the work I do, that's what I'm mostly interested in from the history API (native or third party). Knowing that a history entry with the same UUID can point to different URLs at different points in time is very important information. I'm not necessarily against that, it just needs clarification.

> In particular, this kind of suggests "update" is better than "replace". If we did "replace", then what would happen in the following scenario?

Same as ` history.go(n)` where n points to an entry that doesn't exist: It doesn't navigate. Or, I assume, just like `appHistory.navigateTo("this_key_doesn't_exist");`

> How so? The location object's values change all the time, e.g. using history.replaceState(), or fragment navigation.

In my work, I mostly interact with the browser history through third party libraries. I have confused the "location is immutable" from that with the actual history API behavior. Sorry about that - I should know better, as I have my own such library ;). But that's also the lense I read the proposal through: Would I still need an additional library to make routing in my application reliable and neat. If `AppHistoryEntry`s can mutate while I'm handling them, then the answer is yes.

**Comment by domenic** [comment]
OK, cool, thanks for expanding. I'm considering this a genuine open question, and I'd love input from others on what would be expected and desirable.

**Comment by domenic** [comment]
I chatted with @tbondwilkinson about a few solutions in this space:

One solution for this is to have two separate keys: one "unique identifier" that is changed on replace, and one "slot key" that is not. You use the "slot key" to navigate around (e.g. using this proposal's `appHistory.navigateTo()`), and you use the unique identifier to cache resources.

Another is to provide a stronger linkage between an entry and the one that replaces it. For example, you could have an event that fires on an entry that's going to be replaced, which tells you about the new entry that's replacing it. This would allow you to use the new entry's key for various purposes, since yours is now out of date.

In a similar vein, there could be a link on an app history entry giving you a pointer to the `AppHistoryEntry` it replaced. This also solves a related problem where one of the major goals of this API is to make state reliable, e.g. by allowing introspection of the non-current entry's state. But, when you replace the entry, its state is currently lost.

At a higher level, the question is whether we want to treat entries as immutable or mutable. (`window.history` treats them as mutable for `state`, and immutable for `url` in theory. However, because only the current entry is ever exposed, it appears to the developer as if both `state` and `url` are mutable; that is, there's no update/replace distinction.) Immutability has some nice properties in general, and in particular, it means there's only ever a "replace" operation, and not an "update". But, it does mean you need some stable notion of "slot key" or similar, and you need to define what happens when navigating to a replaced entry, and so on.

**Comment by SetTrend** [comment]
I'd like to chime in on this:

How is the unique key supposed to be composed? Is it a hash of the entry's member values?

Because, if it isn't, an timestamp value (or even an incremental integer value), being constant on the corresponding object, would suffice for example.

I don't think side effects may occur if an entry's member values could be updated from within their corresponding `navigate` event, and locked/frozen afterwards. Anyone think this would be disadvantageous?

**Comment by domenic** [comment]
> How is the unique key supposed to be composed? Is it a hash of the entry's member values?

The current proposal is a browser-generated GUID. An incrementing number would also work (the point is just to be unique within an app history list) but I worried that people would treat that as an index, which it isn't.

**Comment by ljharb** [comment]
Is there any way it could be somewhat deterministic, perhaps based on the URL combined with the timestamp? (or is there always a chance of collision that way)

**Comment by domenic** [comment]
I don't really see a use case for deterministic? That would encourage people to guess the key, which seems bad.

**Comment by domenic** [comment]
Moved to https://github.com/WICG/app-history/issues/7!
